"use client";

import { useEffect, useState } from "react";

interface Heading {
  id: string;
  text: string;
  level: number;
}

export function TableOfContents({ source }: { source: string }) {
  const [headings, setHeadings] = useState<Heading[]>([]);
  const [activeId, setActiveId] = useState<string>("");

  useEffect(() => {
    // We get headings by querying the DOM after MDX renders them, rather than parsing regex here
    // since the IDs are generated by remark-slug or custom logic.
    // Wait for a short tick so MDX rendering completes
    const timer = setTimeout(() => {
      const elements = Array.from(document.querySelectorAll("article .prose h2, article .prose h3"));
      
      if (elements.length > 0) {
        // Only assign IDs if missing
        elements.forEach((el, index) => {
          if (!el.id) {
            el.id = `heading-${index}`;
          }
        });

        const parsedHeadings: Heading[] = elements.map((elem) => ({
          id: elem.id,
          text: elem.textContent || "",
          level: Number(elem.tagName.replace("H", ""))
        }));
        
        setHeadings(parsedHeadings);
      }
    }, 100);

    return () => clearTimeout(timer);
  }, [source]);

  useEffect(() => {
    if (headings.length === 0) return;

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveId(entry.target.id);
          }
        });
      },
      { rootMargin: "0% 0% -80% 0%" }
    );

    headings.forEach((heading) => {
      const el = document.getElementById(heading.id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, [headings]);

  if (headings.length === 0) return null;

  return (
    <div className="my-10 rounded-xl border border-[var(--border)] bg-[var(--surface-1)] px-6 py-8">
      <h2 className="mb-6 text-sm font-bold uppercase tracking-wider text-[var(--text-muted)]">On this page</h2>
      <ul className="space-y-4">
        {headings.map((heading) => (
          <li 
            key={heading.id}
            style={{ paddingLeft: `${(heading.level - 2) * 1.5}rem` }}
            className={`relative text-sm transition-colors ${
              activeId === heading.id 
                ? "toc-active" 
                : "text-[var(--text-secondary)] hover:text-[var(--text-primary)]"
            }`}
          >
            <a 
              href={`#${heading.id}`}
              onClick={(e) => {
                e.preventDefault();
                document.getElementById(heading.id)?.scrollIntoView({ behavior: 'smooth' });
                setActiveId(heading.id);
              }}
              className="block pl-4 leading-relaxed"
            >
              {heading.text}
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
}
